### ISSUE TITLE
Release 0.4.9

### ISSUE THREAD

**Issue by jomo** [tikservices/html5-video-everywhere#108]
I was greeted by this popup today:
![screenshot](https://user-images.githubusercontent.com/3585743/50649458-37531b00-0f7e-11e9-8a09-0c1b92b86757.png)

An extension that requests "all data for all websites" out of nowhere got me curious, and I became suspicious when there were no related commits on this repository.

The changes seem to be minimal, only manifest.json was changed:

```diff
diff --git a/manifest.json b/manifest.json
index 048..049 100644
--- a/manifest.json
+++ b/manifest.json
@@ -1,7 +1,7 @@
 {
   "manifest_version": 2,
   "name": "__MSG_title__",
-  "version": "0.4.8",
+  "version": "0.4.9",
   "description": "__MSG_description__",
   "homepage_url": "https://github.com/lejenome/html5-video-everywhere",
   "author": "Moez Bouhlel",
@@ -115,6 +115,9 @@
     "storage",
     "webRequest",
     "webRequestBlocking",
+    "tabs",
+    "http://*/*",
+    "https://*/*",
     "activeTab",
     "*://www.youtube.com/*",
     "*://*.googlevideo.com/*",
```

As no other code was changed, can you please elaborate why this permission is suddenly required with no change in code? Thank you.

**Comment by lejenome** [comment]
I do not own the hosted version in AMO since a long time.
This repository is an archive of latest version I have maintained.

**Comment by ghost** [comment]
@lejenome then who released v0.5.0 since the WX been blocked/blackedlisted and labelled as malicious https://bugzilla.mozilla.org/show_bug.cgi?id=1525880 ?

**Comment by jomo** [comment]
I'm also interested how/when/why the addon ownership was transferred. @lejenome Did you know the person you passed the ownership to? Did they offer you money?

Also, since the repo has been un-archived and development continued, your commit signature is broken. What's up with that?

![screenshot](https://user-images.githubusercontent.com/3585743/53010753-fdab7600-343e-11e9-9e81-213bc63abf08.png)

**Comment by lejenome** [comment]
The extension is republished to AMO under new name [html5-video-everywhere-next](https://addons.mozilla.org/en-US/firefox/addon/html5-video-everywhere-next/) and a new id `h5vew@tik.tn`

I'm just republishing it for any person interested to use it as it is. I'm not planning to continue developing it or maintaining it or fixing any broken website support because the main reason for developing the extension was to replace the broken custom HTML5 video players on Youtube and other websites but now they are more stabe.

The new version is just an update to the build script and an upgrade of dependencies.

PR/forks are welcome. Maintainers are welcome too.

**Comment by PurHur** [comment]
Please elaborate what has happened to this repo. You look very suspicious here.
