### ISSUE TITLE
doesn't recognize embedded youtube videos in mobafire.com

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [tikservices/html5-video-everywhere#26]
Go to http://www.mobafire.com/league-of-legends/videos and play a video, it try to use flash player instead of html5 (i have shumway and try to use it).

**Comment by lejenome** [comment]
That's expected as they are using `<object>` tag to play videos with flash player version instead of `<frame>` tag which I can redirect to the html5 version.
Fix this case depends on this unfixed issue #1 .
I opened a more generic issue #27 and I'm closing this one just to keep Issues list small.
Thanks for reporting.

**Comment by lejenome** [comment]
There is a good solution as explained on #27 . I recommend you to install [no-flash](https://github.com/hfiguiere/no-flash) addon until a better fix is available.
Discussion is still on #27.

**Comment by Alessandro-Barbieri** [comment]
@lejenome no-flash is awesome, thank you.
