### ISSUE TITLE
[abc.net.au] Paused video results in audio playing from the beginning.

### ISSUE THREAD

**Issue by Hez0** [tikservices/html5-video-everywhere#29]
http://www.abc.net.au/4corners/stories/2015/02/23/4183437.htm

Is anyone else able to replicate this? Just play the video and then pause it. If you spam the pause/play button, you'll get lots of concurrent audio playing.

Thank you for this extension.

**Comment by lejenome** [comment]
1/ The add-on does not support ABC video player. This is just their code using
browser default Video player.
2/ This issue is on their JavaScript code. They don't remove Mouse click event
listener after opening video. So 2 mouse clicks to pause and play video again
cause 2 other video players injected on background.

Contact them to report the issue.
